stages:
    - build
    - test
  
build:
    stage: build
    image: node
    script:
      - cd ./src/Web-App/bingo-app
      - echo "Start building App"
      - npm install
      - CI=false npm run build
      - echo "Build successfully!"
  
test:
    stage: test
    image: node
    script:
      - cd ./src/Web-App/bingo-app
      - echo "Testing App"
      - npm install
      - rm -rf node_modules/eslint
      - CI=false npm test
      - echo "Test successfully!"