stages:
    - build
  
build:
    stage: build
    image: node
    script:
      - cd ./src/Web-App/bingo-app
      - echo "Start building App"
      - npm install
      - CI=false npm run build
      - echo "Build successfully!"